syntax = "proto3";

package rec_room;

import "core/guid_data.proto";
import "core/vector3_data.proto";
import "circuits_v2/circuit_graph_data.proto";
import "circuits_v2/circuit_template_root_data.proto";
import "circuits_v2/reward_data.proto";
import "rec_room/transform_data.proto";
import "rec_room/game_configuration/game_configuration_data.proto";
import "rec_room/game_configuration/game_rule_wrapper_data.proto";
import "rec_room/persistence/deprecated/DEPRECATED_room_persistence_version.proto";
import "rec_room/persistence/deprecated/DEPRECATED_tool_data.proto";
import "rec_room/persistence/ai_data.proto";
import "rec_room/persistence/area_controller_data.proto";
import "rec_room/persistence/audio_effect_zone_data.proto";
import "rec_room/persistence/audio_sampler_data.proto";
import "rec_room/persistence/trail_data.proto";
import "rec_room/persistence/beacon.proto";
import "rec_room/persistence/bounce_pad_data.proto";
import "rec_room/persistence/breakable_object_data.proto";
import "rec_room/persistence/button_data.proto";
import "rec_room/persistence/checkpoint_data.proto";
import "rec_room/persistence/circuit_node_data.proto";
import "rec_room/persistence/configurable_circuit_visibility_data.proto";
import "rec_room/persistence/configurable_physics_settings_data.proto";
import "rec_room/persistence/configurable_selector_data.proto";
import "rec_room/persistence/connectable_node_data.proto";
import "rec_room/persistence/control_panel_circuit_object_data.proto";
import "rec_room/persistence/costume_data.proto";
import "rec_room/persistence/creation_object_data.proto";
import "rec_room/persistence/discovery_storefront_data.proto";
import "rec_room/persistence/drawing_surface_data.proto";
import "rec_room/persistence/dynamic_light_data.proto";
import "rec_room/persistence/explosion_emitter_data.proto";
import "rec_room/persistence/free_gift_button_data.proto";
import "rec_room/persistence/full_body_puppet_tool_data.proto";
import "rec_room/persistence/mannequin_data.proto";
import "rec_room/persistence/game_ai_data.proto";
import "rec_room/persistence/game_role_node_data.proto";
import "rec_room/persistence/glass_pane_data.proto";
import "rec_room/persistence/grabber_data.proto";
import "rec_room/persistence/health_potion_data.proto";
import "rec_room/persistence/holotar_data.proto";
import "rec_room/persistence/image_data.proto";
import "rec_room/persistence/invention_anchor_data.proto";
import "rec_room/persistence/invention_instance_data.proto";
import "rec_room/persistence/invisible_collision_data.proto";
import "rec_room/persistence/invisible_collision_v2_data.proto";
import "rec_room/persistence/laser_pointer_data.proto";
import "rec_room/persistence/leaderboard_data.proto";
import "rec_room/persistence/log_screen.proto";
import "rec_room/persistence/text_screen_data.proto";
import "rec_room/persistence/collision_detection_volume_data.proto";
import "rec_room/persistence/message_data.proto";
import "rec_room/persistence/mood_circuit_data.proto";
import "rec_room/persistence/moveableprop_data.proto";
import "rec_room/persistence/object_group_data.proto";
import "rec_room/persistence/object_spawner_data.proto";
import "rec_room/persistence/particle_emitter_data.proto";
import "rec_room/persistence/persisted_room_version.proto";
import "rec_room/persistence/persisted_sfx_data.proto";
import "rec_room/persistence/player_attractor_data.proto";
import "rec_room/persistence/pool_table_data.proto";
import "rec_room/persistence/poster_data.proto";
import "rec_room/persistence/proximity_mine_data.proto";
import "rec_room/persistence/raycast_gizmo_data.proto";
import "rec_room/persistence/remote_control_data.proto";
import "rec_room/persistence/replicator_data.proto";
import "rec_room/persistence/room_consumable_button_data.proto";
import "rec_room/persistence/room_currency_button_data.proto";
import "rec_room/persistence/room_door_data.proto";
import "rec_room/persistence/room_door_v2_data.proto";
import "rec_room/persistence/sandbox_colorable_data.proto";
import "rec_room/persistence/sandbox_deformation_data.proto";
import "rec_room/persistence/sandbox_gizmo_data.proto";
import "rec_room/persistence/scoreboard_setup_data.proto";
import "rec_room/persistence/seat_data.proto";
import "rec_room/persistence/security_data.proto";
import "rec_room/persistence/set_leaderboard_stat_data.proto";
import "rec_room/persistence/set_tags_node_data.proto";
import "rec_room/persistence/shape_data.proto";
import "rec_room/persistence/spawn_point_data.proto";
import "rec_room/persistence/spawnable_tool_data.proto";
import "rec_room/persistence/spawnpoint_spawner_data.proto";
import "rec_room/persistence/keepsake_data.proto";
import "rec_room/persistence/sticky_data.proto";
import "rec_room/persistence/streaming_camera_point_data.proto";
import "rec_room/persistence/super_room_version.proto";
import "rec_room/persistence/swing_handle_data.proto";
import "rec_room/persistence/synced_data.proto";
import "rec_room/persistence/tagged_tool_data.proto";
import "rec_room/persistence/text_label_data.proto";
import "rec_room/persistence/throw_handle_data.proto";
import "rec_room/persistence/tool_cleanup_data.proto";
import "rec_room/persistence/tool_entity_data.proto";
import "rec_room/persistence/tool_holder_data.proto";
import "rec_room/persistence/trigger_handle_data.proto";
import "rec_room/persistence/trigger_volume_data.proto";
import "rec_room/persistence/ugc_steering_data.proto";
import "rec_room/persistence/ugc_steering_engine_data.proto";
import "rec_room/persistence/ugc_storefront_data.proto";
import "rec_room/persistence/vehicle_data.proto";
import "rec_room/persistence/interaction_volume_data.proto";
import "rec_room/persistence/player_event_broadcast_volume_data.proto";
import "rec_room/persistence/persisted_audio_player_data.proto";
import "rec_room/persistence/projectile_launcher_data.proto";
import "rec_room/persistence/remote_video_player_data.proto";
import "rec_room/persistence/ranged_weapon_prop_data.proto";
import "rec_room/persistence/welcome_mat_v2_data.proto";
import "rec_room/persistence/gun_handle_data.proto";
import "rec_room/persistence/spawn_point_v2_data.proto";
import "rec_room/persistence/dialogue_ui_data.proto";
import "rec_room/persistence/base_handle_data.proto";
import "rec_room/persistence/melee_weapon_data.proto";
import "rec_room/persistence/textured_quad_data.proto";
import "rec_room/persistence/sandbox_avatar_item_display_data.proto";

option csharp_namespace = "RecRoom.Protobuf";

message PersistenceViewData {
  bytes id = 1;
  bool DEPRECATED_is_scene_object = 2;
  repeated .rec_room.ChildPersistenceViewData child_views = 3;
  .rec_room.ToolEntityData tool_entity_data = 9;
  .rec_room.TransformData transform = 10;
  .rec_room.SpawnableToolData spawnable_tool_data = 11;
  .rec_room.ShapeContainerData shape_container_data = 12;
  .rec_room.DEPRECATED_ToolData DEPRECATED_tool_data = 13;
  .rec_room.CreationObjectData creation_object_data = 14;
  .rec_room.TaggedToolData tagged_tool_data = 15;
  .rec_room.StickyData sticky_data = 16;
  .rec_room.DrawingSurfaceData drawing_surface_data = 17;
  .rec_room.ImageData image_data = 18;
  .rec_room.ToolHolderData tool_holder_data = 19;
  .rec_room.RemoteControlData remote_control_data = 20;
  .rec_room.RoomDoorData room_door_data = 21;
  .rec_room.ToolCleanupData tool_cleanup_data = 22;
  .rec_room.SpawnPointSpawnerData spawnpoint_spawner_data = 23;
  .rec_room.PersistedSFXData persisted_sfx_data = 24;
  .rec_room.CircuitNodeData circuit_node_data = 25;
  .rec_room.MessageData message_data = 26;
  .rec_room.HolotarPersistenceData holotar_persistence_Data = 27;
  .rec_room.SpawnPointData spawn_point_data = 28;
  .rec_room.AudioSamplerPersistenceData audio_sampler_persistence_data = 29;
  .rec_room.ButtonData button_data = 30;
  .rec_room.TriggerVolumeData trigger_volume_data = 31;
  .rec_room.SandboxGizmoData sandbox_gizmo_data = 32;
  .rec_room.ObjectSpawnPointData object_spawn_point_data = 33;
  .rec_room.SetTagsNodeData set_tags_node_data = 34;
  .rec_room.BreakableObjectData breakable_object_data = 35;
  .rec_room.SandboxColorableData sandbox_colorable_data = 36;
  .rec_room.ParticleEmitterData particle_emitter_data = 37;
  .rec_room.ObjectGroupData object_group_data = 38;
  .rec_room.StateMachineStateData state_machine_state_data = 39;
  .rec_room.GameConfigurationData game_configuration_data = 40;
  .rec_room.GameRuleWrapperData game_rule_wrapper_data = 41;
  .rec_room.HealthPotionData health_potion_data = 42;
  .rec_room.ScoreboardSetupData scoreboard_setup_data = 43;
  .rec_room.SpotlightData spotlight_data = 44;
  .rec_room.DynamicLightData dynamic_light_data = 45;
  .rec_room.BouncePadData bounce_pad_data = 46;
  .rec_room.CheckpointData checkpoint_data = 47;
  .rec_room.LeaderboardData leaderboard_data = 48;
  .rec_room.SetLeaderboardStatData set_leaderboard_stat_data = 49;
  .rec_room.GameRoleNodeData game_role_node_data = 50;
  .rec_room.PlayerAttractorData player_attractor_data = 51;
  .rec_room.ToggleButtonData toggle_button_data = 52;
  .rec_room.SandboxDeformationData sandbox_deformation_data = 53;
  .rec_room.TextLabelData text_label_data = 54;
  .rec_room.ProximityMineData proximity_mine_data = 55;
  .rec_room.InvisibleCollisionData invisible_collision_data = 56;
  .rec_room.MoodCircuitData mood_circuit_data = 57;
  .rec_room.AIData ai_data = 58;
  .rec_room.UGCSpawnerData ugc_spawner_data = 59;
  .rec_room.LinkButtonData link_button_data = 60;
  .rec_room.RaycastGizmoData raycast_gizmo_data = 61;
  .rec_room.CostumeData costume_data = 62;
  .rec_room.FreeGiftButtonData free_gift_button_data = 63;
  .rec_room.AreaData area_data = 64;
  .rec_room.ControlPanelCircuitObjectData control_panel_data = 65;
  .rec_room.AreaControllerData area_controller_data = 66;
  .rec_room.ShowcasePosterData showcase_poster_data = 67;
  .rec_room.LogScreenData log_screen_data = 68;
  .rec_room.AudioEffectZoneData audio_effect_zone_data = 69;
  .rec_room.GlassPaneData glass_pane_data = 70;
  .rec_room.ConfigurableSelectorData DEPRECATED_configurable_selector_data = 71;
  repeated .rec_room.ConfigurableSelectorData configurable_selectors = 72;
  .rec_room.StreamingCameraPointData streaming_camera_point_data = 73;
  .rec_room.RoomCurrencyButtonData room_currency_button_data = 74;
  .rec_room.ConfigurableCircuitVisibilityData configurable_circuit_visibility_data = 75;
  .rec_room.SeatData seat_data = 76;
  .rec_room.MoveablePropData moveable_prop_data = 77;
  .rec_room.SyncedData synced_data = 78;
  .rec_room.RoomConsumableButtonData room_consumable_button_data = 79;
  .rec_room.GroundVehicleData ground_vehicle_data = 80;
  .rec_room.VehicleEngineData vehicle_engine_data = 81;
  .rec_room.WheelDifferentialData wheel_differential_data = 82;
  .rec_room.WheelSuspensionSystemData wheel_suspension_system_data = 83;
  .rec_room.TriggerHandleData trigger_handle_data = 84;
  .rec_room.InteractionVolumeData interaction_volume_data = 85;
  .rec_room.PoolTableData pool_table_data = 86;
  .rec_room.PlayerEventBroadcastVolumeData player_event_broadcast_volume_data = 87;
  .rec_room.UGCStorefrontData ugc_storefront_data = 88;
  .rec_room.ProjectileLauncherData projectile_launcher_data = 89;
  .rec_room.PersistedAudioPlayerData audio_player_data = 90;
  .rec_room.DomeLightData dome_light_data = 91;
  .rec_room.RemoteVideoPlayerData remote_video_player_data = 92;
  .rec_room.ExplosionEmitterData explosion_emitter_data = 93;
  .rec_room.InvisibleCollisionV2Data invisible_collision_v2_data = 94;
  .rec_room.ConfigurablePhysicsSettingsData configurable_physics_settings_data = 95;
  .rec_room.GunHandleData gun_handle_data = 96;
  .rec_room.SpawnPointV2Data spawn_point_v2_data = 97;
  .rec_room.WelcomeMatV2Data welcome_mat_v2_data = 98;
  .rec_room.BeaconData beacon_data = 99;
  int32 encoded_entity_idx = 100;
  .rec_room.TextScreenData text_screen_data = 101;
  .rec_room.RoomDoorV2Data room_door_v2_data = 102;
  .rec_room.KeepsakeData keepsake_data = 103;
  .rec_room.LaserPointerData laser_pointer_data = 104;
  .rec_room.CollisionDetectionVolumeData collision_detection_volume_data = 105;
  .rec_room.SwingHandleData swing_handle_data = 106;
  .rec_room.TrailData trail_data = 107;
  .rec_room.FullBodyPuppetToolData full_body_puppet_tool_data = 108;
  .rec_room.ThrowHandleData throw_handle_data = 110;
  .rec_room.DialogueUIData dialogue_ui_data = 111;
  .rec_room.GrabberData grabber_data = 112;
  .rec_room.ReplicatorData replicator_data = 113;
  .rec_room.BaseHandleData base_handle_data = 114;
  .rec_room.RangedWeaponPropData ranged_weapon_data = 115;
  .rec_room.UGCSteeringEngineData ugc_steering_engine_data = 116;
  .rec_room.UGCSteeringData ugc_steering_data = 117;
  .rec_room.SharedRangedWeaponData shared_ranged_weapon_data = 118;
  .rec_room.MeleeWeaponData melee_weapon_data = 119;
  .rec_room.MannequinData mannequin_data = 120;
  .rec_room.GameAIData game_ai_data = 121;
  .rec_room.TexturedQuadData textured_quad_data = 122;
  .rec_room.DiscoveryStorefrontData discovery_storefront_data = 123;
  .rec_room.SandboxAvatarItemDisplayData sandbox_avatar_item_display_data = 124;
  reserved 109;
}

message ChildPersistenceViewData {
  int32 child_id = 1;
  .rec_room.PersistenceViewData data = 2;
}

message UGCSpawnerData {
  int32 time_between_spawns_ms = 1;
  int32 DEPRECATED_tool_type = 2;
  int64 invention_id = 3;
  int32 num_objects_to_spawn = 4;
  int32 apply_tags_to_spawned_objects = 5;
  .rec_room.SpawnableTemplateData template_data = 6;
  bytes preview_circuit_graph_id = 7;
  .core.GuidData tool_type = 8;
}

message SpawnableTemplateData {
  .rec_room.DEPRECATED_RoomPersistenceVersion DEPRECATED_room_data_version = 1;
  repeated .rec_room.PersistenceViewData persistence_views = 2;
  string output_log = 3;
  bytes circuit_data = 4;
  .rec_room.ConnectableGraphData connectable_graph_data = 5;
  .core.Vector3Data extents = 6;
  .circuits_v2.CircuitGraphData DEPRECATED_circuit_v2_data = 7;
  .circuits_v2.CircuitTemplateRootData circuit_v2_data = 8;
  .rec_room.InventionAnchorData invention_anchor_data = 9;
  .rec_room.PersistedRoomVersion persisted_room_version = 10;
  bytes object_model_data = 11;
  .rec_room.SuperRoomVersion super_room_version = 12;
  .rec_room.InventionInstanceData invention_instance_data = 13;
  .rec_room.SecurityData security_data = 14;
  repeated bytes inventory_item_dtos = 15;
  repeated bytes room_offer_dtos = 16;
  repeated .circuits_v2.RewardData reward_datas = 17;
  repeated bytes inventory_item_tag_dtos = 18;
}
